import { Anuphan } from 'next/font/google'
import './globals.css'


const anuphan = Anuphan({ subsets: ['thai'] })

export const metadata = {
  title: 'Admin Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={anuphan.className}>
        {children}
      </body>
    </html>
    )
}
